import {createServerFn} from '@tanstack/react-start'
import {getCookie} from '@tanstack/react-start/server'
import {queryOptions} from '@tanstack/react-query'
import {getSupabaseAdminClient,getSupabaseServerClient} from './supabase/server'
import type {Json} from '@/types/database'
const configured=()=>Boolean(process.env.VITE_SUPABASE_URL&&process.env.VITE_SUPABASE_ANON_KEY)
const bytes=(value:string)=>new TextEncoder().encode(value)
const encode=(value:Uint8Array)=>Buffer.from(value).toString('base64url')
const decode=(value:string)=>new Uint8Array(Buffer.from(value,'base64url'))
async function encryptionKey(){const material=process.env.INTEGRATION_ENCRYPTION_KEY;if(!material)throw new Error('Integration encryption is not configured.');return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',bytes(material)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12)),body=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(),bytes(value));return `${encode(iv)}.${encode(new Uint8Array(body))}`}
async function decrypt(value:string){const [iv,body]=value.split('.');const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(iv)},await encryptionKey(),decode(body));return new TextDecoder().decode(clear)}
async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes(value.trim().toLowerCase())))).map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function vendorContext(){if(!configured())return null;const token=getCookie('ndh_access_token');if(!token)throw new Error('Authentication required.');const client=getSupabaseServerClient(token),{data:{user}}=await client.auth.getUser(token);if(!user)throw new Error('Session expired.');const {data:vendor}=await client.from('vendors').select('id,shop_slug,meta_pixel_id,meta_capi_token_encrypted').eq('owner_user_id',user.id).single();if(!vendor)throw new Error('Vendor workspace not found.');return{client,vendor}}
export const getMetaSettings=createServerFn({method:'GET'}).handler(async()=>{const auth=await vendorContext();if(!auth)return{configured:false,pixelId:'',hasToken:false,slug:'amari-atelier',events:[]};const {data:events}=await auth.client.from('meta_events').select('id,event_name,status,failure_reason,created_at').eq('vendor_id',auth.vendor.id).order('created_at',{ascending:false}).limit(12);return{configured:true,pixelId:auth.vendor.meta_pixel_id??'',hasToken:Boolean(auth.vendor.meta_capi_token_encrypted),slug:auth.vendor.shop_slug,events:events??[]}})
export const saveMetaSettings=createServerFn({method:'POST'}).validator((value:{pixelId:string;accessToken?:string})=>value).handler(async({data})=>{const auth=await vendorContext();if(!auth)return{ok:true,error:null};const pixel=data.pixelId.trim();if(pixel&&!/^\d{5,30}$/.test(pixel))return{ok:false,error:'Enter a valid numeric Meta Pixel ID.'};try{const update:{meta_pixel_id:string|null;meta_capi_token_encrypted?:string}={meta_pixel_id:pixel||null};if(data.accessToken?.trim())update.meta_capi_token_encrypted=await encrypt(data.accessToken.trim());const {error}=await getSupabaseAdminClient().from('vendors').update(update).eq('id',auth.vendor.id);if(error)throw error;return{ok:true,error:null}}catch(error){return{ok:false,error:error instanceof Error?error.message:'Unable to save Meta settings.'}}})
export const clearMetaToken=createServerFn({method:'POST'}).handler(async()=>{const auth=await vendorContext();if(!auth)return{ok:true};await getSupabaseAdminClient().from('vendors').update({meta_capi_token_encrypted:null}).eq('id',auth.vendor.id);return{ok:true}})
type TrackInput={slug:string;eventName:'ViewContent'|'AddToCart'|'InitiateCheckout';eventId:string;sourceUrl:string;currency:string;value:number;productIds:string[];userAgent?:string}
export const trackMetaEvent=createServerFn({method:'POST'}).validator((value:TrackInput)=>value).handler(async({data})=>{if(!configured())return{ok:true};const admin=getSupabaseAdminClient(),{data:vendor}=await admin.from('vendors').select('id,meta_pixel_id,meta_capi_token_encrypted').eq('shop_slug',data.slug).eq('published',true).maybeSingle();if(!vendor?.meta_pixel_id||!vendor.meta_capi_token_encrypted)return{ok:true};const cleanId=data.eventId.replace(/[^a-zA-Z0-9_.:-]/g,'').slice(0,100);const payload={event_name:data.eventName,event_time:Math.floor(Date.now()/1000),event_id:cleanId,event_source_url:data.sourceUrl,action_source:'website',user_data:{client_user_agent:data.userAgent},custom_data:{currency:data.currency,value:Math.max(0,data.value),content_ids:data.productIds.slice(0,100),content_type:'product'}};const {data:event,error}=await admin.from('meta_events').insert({vendor_id:vendor.id,event_name:data.eventName,event_id:cleanId,source_url:data.sourceUrl,payload:payload as Json}).select('id').single();if(error?.code==='23505')return{ok:true};if(error||!event)return{ok:false};try{const token=await decrypt(vendor.meta_capi_token_encrypted),response=await fetch(`https://graph.facebook.com/${process.env.META_GRAPH_API_VERSION||'v23.0'}/${vendor.meta_pixel_id}/events?access_token=${encodeURIComponent(token)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:[payload]})}),body=await response.json().catch(()=>({})) as Json;if(!response.ok)throw new Error(JSON.stringify(body));await admin.from('meta_events').update({status:'sent',provider_response:body,sent_at:new Date().toISOString()}).eq('id',event.id);return{ok:true}}catch(error){await admin.from('meta_events').update({status:'failed',failure_reason:error instanceof Error?error.message.slice(0,500):'Meta request failed'}).eq('id',event.id);return{ok:false}}})
export const metaSettingsQuery=()=>queryOptions({queryKey:['dashboard','meta'],queryFn:()=>getMetaSettings(),staleTime:30_000})

export async function sendMetaPurchase(orderId:string){if(!configured())return;const admin=getSupabaseAdminClient(),{data:order}=await admin.from('orders').select('id,vendor_id,customer_email,customer_phone,currency,total').eq('id',orderId).maybeSingle();if(!order)return;const [{data:vendor},{data:items}]=await Promise.all([admin.from('vendors').select('meta_pixel_id,meta_capi_token_encrypted,shop_slug').eq('id',order.vendor_id).maybeSingle(),admin.from('order_items').select('product_id,quantity').eq('order_id',order.id)]);if(!vendor?.meta_pixel_id||!vendor.meta_capi_token_encrypted)return;const eventId=`purchase-${order.id}`,emailHash=await digest(order.customer_email),phoneHash=order.customer_phone?await digest(order.customer_phone.replace(/\D/g,'')):null,payload={event_name:'Purchase',event_time:Math.floor(Date.now()/1000),event_id:eventId,event_source_url:`${process.env.PUBLIC_APP_URL??'https://ndh.com.ng'}/store/${vendor.shop_slug}`,action_source:'website',user_data:{em:[emailHash],...(phoneHash?{ph:[phoneHash]}:{})},custom_data:{currency:order.currency,value:Number(order.total),content_ids:(items??[]).map(item=>item.product_id),contents:(items??[]).map(item=>({id:item.product_id,quantity:item.quantity})),content_type:'product'}};const {data:event,error}=await admin.from('meta_events').insert({vendor_id:order.vendor_id,event_name:'Purchase',event_id:eventId,source_url:payload.event_source_url,order_id:order.id,payload:payload as Json}).select('id').single();if(error?.code==='23505')return;if(error||!event)return;try{const response=await fetch(`https://graph.facebook.com/${process.env.META_GRAPH_API_VERSION||'v23.0'}/${vendor.meta_pixel_id}/events?access_token=${encodeURIComponent(await decrypt(vendor.meta_capi_token_encrypted))}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:[payload]})}),body=await response.json().catch(()=>({})) as Json;if(!response.ok)throw new Error(JSON.stringify(body));await admin.from('meta_events').update({status:'sent',provider_response:body,sent_at:new Date().toISOString()}).eq('id',event.id)}catch(error){await admin.from('meta_events').update({status:'failed',failure_reason:error instanceof Error?error.message.slice(0,500):'Meta request failed'}).eq('id',event.id)}}
