import {createServerFn} from '@tanstack/react-start'
import {getCookie} from '@tanstack/react-start/server'
import {queryOptions} from '@tanstack/react-query'
import {getSupabaseAdminClient,getSupabaseServerClient} from './supabase/server'
import type {Json} from '@/types/database'

const configured=()=>Boolean(process.env.VITE_SUPABASE_URL&&process.env.VITE_SUPABASE_ANON_KEY)
async function context(){if(!configured())return null;const token=getCookie('ndh_access_token');if(!token)throw new Error('Authentication required.');const client=getSupabaseServerClient(token);const {data:{user}}=await client.auth.getUser(token);if(!user)throw new Error('Session expired.');const {data:vendor}=await client.from('vendors').select('id,business_name').eq('owner_user_id',user.id).single();if(!vendor)throw new Error('Vendor workspace not found.');return{client,vendor}}
async function paystack(path:string,init?:RequestInit){const key=process.env.PAYSTACK_SECRET_KEY;if(!key)throw new Error('Paystack is not configured.');const response=await fetch(`https://api.paystack.co${path}`,{...init,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json',...init?.headers}});const body=await response.json().catch(()=>null) as {status?:boolean;message?:string;data?:unknown}|null;if(!response.ok||!body?.status)throw new Error(body?.message??'Paystack request failed.');return body.data}
export const getPayoutDashboard=createServerFn({method:'GET'}).handler(async()=>{const auth=await context();if(!auth)return{configured:false,ledger:{gross:2482900,platform_fees:37244,processing_fees:22500,paid_out:1200000,pending_payouts:0,available:1223156},accounts:[{id:'demo-account',bank_code:'058',bank_name:'GTBank',account_name:'AMARI ATELIER',account_number_last4:'2794',is_default:true}],payouts:[]};const [{data:ledgerRows,error:ledgerError},{data:accounts,error:accountError},{data:payouts,error:payoutError}]=await Promise.all([auth.client.rpc('vendor_ngn_ledger',{target_vendor_id:auth.vendor.id}),auth.client.from('payout_accounts').select('id,bank_code,bank_name,account_name,account_number_last4,is_default,verified_at').eq('vendor_id',auth.vendor.id).order('is_default',{ascending:false}),auth.client.from('payouts').select('id,amount,currency,status,bank_account_snapshot,provider_reference,failure_reason,requested_at,processed_at').eq('vendor_id',auth.vendor.id).order('requested_at',{ascending:false}).limit(30)]);if(ledgerError||accountError||payoutError)throw new Error('Unable to load payout ledger.');return{configured:true,ledger:ledgerRows?.[0]??{gross:0,platform_fees:0,processing_fees:0,paid_out:0,pending_payouts:0,available:0},accounts:accounts??[],payouts:payouts??[]}})
export const listNigerianBanks=createServerFn({method:'GET'}).handler(async()=>{if(!process.env.PAYSTACK_SECRET_KEY)return[{name:'Access Bank',code:'044'},{name:'First Bank of Nigeria',code:'011'},{name:'Guaranty Trust Bank',code:'058'},{name:'United Bank for Africa',code:'033'},{name:'Zenith Bank',code:'057'}];try{const result=await paystack('/bank?country=nigeria&currency=NGN&perPage=100');return((result as Array<{name:string;code:string;active?:boolean}>).filter(bank=>bank.active!==false).map(({name,code})=>({name,code})))}catch{return[]}})
export const addPayoutAccount=createServerFn({method:'POST'}).validator((value:{bankCode:string;bankName:string;accountNumber:string;makeDefault:boolean})=>value).handler(async({data})=>{const auth=await context();if(!auth)return{ok:true,error:null};const number=data.accountNumber.replace(/\D/g,'');if(number.length!==10)return{ok:false,error:'Nigerian account numbers must contain ten digits.'};try{const resolution=await paystack(`/bank/resolve?account_number=${number}&bank_code=${encodeURIComponent(data.bankCode)}`) as {account_name?:string;account_number?:string};if(!resolution.account_name)throw new Error('The account name could not be verified.');const recipient=await paystack('/transferrecipient',{method:'POST',body:JSON.stringify({type:'nuban',name:resolution.account_name,account_number:number,bank_code:data.bankCode,currency:'NGN'})}) as {recipient_code?:string};if(!recipient.recipient_code)throw new Error('Paystack did not create a transfer recipient.');const admin=getSupabaseAdminClient();if(data.makeDefault)await admin.from('payout_accounts').update({is_default:false}).eq('vendor_id',auth.vendor.id);const {error}=await admin.from('payout_accounts').insert({vendor_id:auth.vendor.id,bank_code:data.bankCode,bank_name:data.bankName,account_name:resolution.account_name,account_number_last4:number.slice(-4),provider_recipient_code:recipient.recipient_code,is_default:data.makeDefault});if(error)throw new Error('Unable to save this bank account.');return{ok:true,error:null}}catch(error){return{ok:false,error:error instanceof Error?error.message:'Unable to verify bank account.'}}})
export const removePayoutAccount=createServerFn({method:'POST'}).validator((id:string)=>id).handler(async({data})=>{const auth=await context();if(!auth)return{ok:true,error:null};const {error}=await auth.client.from('payout_accounts').delete().eq('id',data).eq('vendor_id',auth.vendor.id);return error?{ok:false,error:'Unable to remove bank account.'}:{ok:true,error:null}})
export const requestPayout=createServerFn({method:'POST'}).validator((value:{accountId:string;amount:number})=>value).handler(async({data})=>{const auth=await context();if(!auth)return{ok:true,error:null,payoutId:'demo-payout',queued:false};const {data:payout,error}=await auth.client.rpc('request_vendor_payout',{target_account_id:data.accountId,requested_amount:data.amount});if(error){if(error.message.includes('Insufficient'))return{ok:false,error:'The requested amount exceeds your available balance.',payoutId:null,queued:false};return{ok:false,error:error.message.includes('Minimum')?'Minimum payout is ₦1,000.':'Unable to create payout request.',payoutId:null,queued:false}}const row=payout as unknown as {id:string;amount:number;bank_account_snapshot:Record<string,unknown>};const reference=`NDH-PAYOUT-${row.id}`;const admin=getSupabaseAdminClient();await admin.from('payouts').update({provider_reference:reference}).eq('id',row.id);try{await paystack('/transfer',{method:'POST',body:JSON.stringify({source:'balance',amount:Math.round(row.amount*100),recipient:String(row.bank_account_snapshot.recipient_code),reason:`NDH Estore vendor payout ${row.id}`,reference})});await admin.from('payouts').update({status:'processing',failure_reason:null}).eq('id',row.id);await admin.from('payout_events').insert({payout_id:row.id,event_type:'submitted',provider_event_id:`submitted:${reference}`,payload:{reference} as Json});return{ok:true,error:null,payoutId:row.id,queued:false}}catch(error){await admin.from('payouts').update({failure_reason:error instanceof Error?error.message:'Transfer submission failed'}).eq('id',row.id);return{ok:true,error:'Your payout was queued and will be retried securely.',payoutId:row.id,queued:true}}})
export const payoutDashboardQuery=()=>queryOptions({queryKey:['dashboard','payouts'],queryFn:()=>getPayoutDashboard(),staleTime:15_000})
export async function processPaystackTransferEvent(eventType:string,data:Record<string,unknown>){const reference=String(data.reference??'');if(!reference.startsWith('NDH-PAYOUT-'))return false;const admin=getSupabaseAdminClient();const {data:payout}=await admin.from('payouts').select('id,status').eq('provider_reference',reference).maybeSingle();if(!payout)return false;const providerEventId=`${eventType}:${String(data.id??reference)}`;const insert=await admin.from('payout_events').insert({payout_id:payout.id,event_type:eventType,provider_event_id:providerEventId,payload:data as Json});if(insert.error?.code==='23505')return true;if(insert.error)throw new Error('Unable to record payout event.');const status=eventType==='transfer.success'?'paid':eventType==='transfer.failed'||eventType==='transfer.reversed'?'failed':null;if(status)await admin.from('payouts').update({status,processed_at:new Date().toISOString(),failure_reason:status==='failed'?String(data.reason??eventType):null}).eq('id',payout.id);return true}
