import {createServerFn} from '@tanstack/react-start'
import {getCookie} from '@tanstack/react-start/server'
import {queryOptions} from '@tanstack/react-query'
import {getSupabaseServerClient} from './supabase/server'
import type {CargoProfile,DeliveryZone} from './storefront'

const configured=()=>Boolean(process.env.VITE_SUPABASE_URL&&process.env.VITE_SUPABASE_ANON_KEY)
async function vendorContext(){if(!configured())return null;const token=getCookie('ndh_access_token');if(!token)throw new Error('Authentication required.');const client=getSupabaseServerClient(token);const {data:{user}}=await client.auth.getUser(token);if(!user)throw new Error('Your session has expired.');const {data:vendor}=await client.from('vendors').select('id,business_category,subscription_tier').eq('owner_user_id',user.id).single();if(!vendor)throw new Error('Vendor workspace not found.');const {data:hasAccess}=await client.rpc('vendor_has_platform_access',{target_vendor_id:vendor.id});if(!hasAccess)throw new Error('Your subscription has expired. Renew from Billing to manage shipping.');return{client,vendor}}
export type ZoneInput={id?:string;countryCode:string;state:string;zoneName:string;fee:number;estimatedDaysMin:number|null;estimatedDaysMax:number|null;active:boolean}
export type CargoInput={id?:string;name:string;originCountry:string;destinationCountry:string;transportMode:'air'|'ocean'|'road'|'rail';metric:'kg'|'cbm'|'flat';rate:number;currency:'NGN'|'USD'|'GBP';minimumCharge:number;active:boolean}
function validateZone(value:ZoneInput){if(!/^[A-Z]{2}$/.test(value.countryCode))return 'Use a valid two-letter country code.';if(value.state.trim().length<2||value.zoneName.trim().length<2)return 'Enter the state and regional zone name.';if(!Number.isFinite(value.fee)||value.fee<0)return 'Delivery fee cannot be negative.';if(value.estimatedDaysMin!==null&&value.estimatedDaysMin<0)return 'Minimum delivery days cannot be negative.';if(value.estimatedDaysMax!==null&&value.estimatedDaysMin!==null&&value.estimatedDaysMax<value.estimatedDaysMin)return 'Maximum delivery days must be greater than the minimum.';return null}
function validateCargo(value:CargoInput){if(value.name.trim().length<2)return 'Enter a profile name.';if(!/^[A-Z]{2}$/.test(value.originCountry)||!/^[A-Z]{2}$/.test(value.destinationCountry))return 'Use valid two-letter origin and destination codes.';if(!Number.isFinite(value.rate)||value.rate<0||!Number.isFinite(value.minimumCharge)||value.minimumCharge<0)return 'Rates and minimum charges cannot be negative.';return null}
export const getShippingProfiles=createServerFn({method:'GET'}).handler(async()=>{const context=await vendorContext();if(!context)return{configured:false,businessCategory:'wigs_fashion',zones:[{id:'zone-1',country_code:'NG',state:'Lagos',zone_name:'Lagos Central',fee:2500,estimated_days_min:1,estimated_days_max:2},{id:'zone-2',country_code:'NG',state:'Lagos',zone_name:'Lagos Island',fee:3500,estimated_days_min:1,estimated_days_max:3},{id:'zone-3',country_code:'NG',state:'Lagos',zone_name:'Lagos Outskirts',fee:5000,estimated_days_min:2,estimated_days_max:4}] as DeliveryZone[],cargo:[{id:'cargo-1',name:'UK Air Freight',origin_country:'NG',destination_country:'GB',transport_mode:'air',metric:'kg',rate:12000,currency:'NGN',minimum_charge:12000}] as CargoProfile[]};const [{data:zones,error:zoneError},{data:cargo,error:cargoError}]=await Promise.all([context.client.from('shipping_zones').select('id,country_code,state,zone_name,fee,estimated_days_min,estimated_days_max,active').eq('vendor_id',context.vendor.id).order('state').order('fee'),context.client.from('cargo_profiles').select('id,name,origin_country,destination_country,transport_mode,metric,rate,currency,minimum_charge,active').eq('vendor_id',context.vendor.id).order('created_at')]);if(zoneError||cargoError)throw new Error('Unable to load shipping profiles.');return{configured:true,businessCategory:context.vendor.business_category,zones:zones??[],cargo:cargo??[]}})
export const saveShippingZone=createServerFn({method:'POST'}).validator((value:ZoneInput)=>value).handler(async({data})=>{const validation=validateZone(data);if(validation)return{ok:false,error:validation};const context=await vendorContext();if(!context)return{ok:true,error:null};if(context.vendor.subscription_tier==='starter'&&!data.id){const {count}=await context.client.from('shipping_zones').select('id',{count:'exact',head:true}).eq('vendor_id',context.vendor.id).eq('country_code',data.countryCode).eq('state',data.state.trim());if((count??0)>=1)return{ok:false,error:'Starter supports one flat delivery fee per state. Upgrade to Pro for regional sub-zones.'}}const values={vendor_id:context.vendor.id,country_code:data.countryCode,state:data.state.trim(),zone_name:data.zoneName.trim(),fee:data.fee,estimated_days_min:data.estimatedDaysMin,estimated_days_max:data.estimatedDaysMax,active:data.active};const result=data.id?await context.client.from('shipping_zones').update(values).eq('id',data.id).eq('vendor_id',context.vendor.id):await context.client.from('shipping_zones').insert(values);if(result.error?.code==='23505')return{ok:false,error:'A zone with this state and name already exists.'};return result.error?{ok:false,error:'Unable to save delivery zone.'}:{ok:true,error:null}})
export const deleteShippingZone=createServerFn({method:'POST'}).validator((id:string)=>id).handler(async({data})=>{const context=await vendorContext();if(!context)return{ok:true,error:null};const {error}=await context.client.from('shipping_zones').delete().eq('id',data).eq('vendor_id',context.vendor.id);return error?{ok:false,error:'Unable to remove delivery zone.'}:{ok:true,error:null}})
export const saveCargoProfile=createServerFn({method:'POST'}).validator((value:CargoInput)=>value).handler(async({data})=>{const validation=validateCargo(data);if(validation)return{ok:false,error:validation};const context=await vendorContext();if(!context)return{ok:true,error:null};if(context.vendor.subscription_tier!=='global_enterprise')return{ok:false,error:'International cargo profiles require the Global Enterprise plan.'};const values={vendor_id:context.vendor.id,name:data.name.trim(),origin_country:data.originCountry,destination_country:data.destinationCountry,transport_mode:data.transportMode,metric:data.metric,rate:data.rate,currency:data.currency,minimum_charge:data.minimumCharge,active:data.active};const result=data.id?await context.client.from('cargo_profiles').update(values).eq('id',data.id).eq('vendor_id',context.vendor.id):await context.client.from('cargo_profiles').insert(values);return result.error?{ok:false,error:'Unable to save cargo profile.'}:{ok:true,error:null}})
export const deleteCargoProfile=createServerFn({method:'POST'}).validator((id:string)=>id).handler(async({data})=>{const context=await vendorContext();if(!context)return{ok:true,error:null};const {error}=await context.client.from('cargo_profiles').delete().eq('id',data).eq('vendor_id',context.vendor.id);return error?{ok:false,error:'Unable to remove cargo profile.'}:{ok:true,error:null}})
export const shippingProfilesQuery=()=>queryOptions({queryKey:['dashboard','shipping'],queryFn:()=>getShippingProfiles(),staleTime:20_000})
