import {createServerFn} from '@tanstack/react-start'
import {getCookie} from '@tanstack/react-start/server'
import {queryOptions} from '@tanstack/react-query'
import {getSupabaseServerClient} from './supabase/server'
import type {Database} from '@/types/database'
import {dispatchOrderEmails} from './email'

type OrderStatus=Database['public']['Enums']['order_status']
export type VendorOrderItem={id:string;product_id:string|null;variant_id:string|null;product_name:string;variant_description:string|null;quantity:number;unit_price:number;total_price:number}
export type VendorOrder={id:string;order_number:number;customer_name:string;customer_email:string;customer_phone:string|null;status:OrderStatus;payment_provider:string|null;payment_reference:string|null;currency:string;subtotal:number;shipping_fee:number;platform_fee:number;total:number;shipping_address:{country_code?:string;state?:string;zone?:string;address?:string}|null;customer_note:string|null;paid_at:string|null;created_at:string;items:VendorOrderItem[]}
export type OrderFilters={status:'all'|OrderStatus;search:string;page:number}
const pageSize=12,configured=()=>Boolean(process.env.VITE_SUPABASE_URL&&process.env.VITE_SUPABASE_ANON_KEY)
async function vendorContext(){if(!configured())return null;const token=getCookie('ndh_access_token');if(!token)throw new Error('Authentication required.');const client=getSupabaseServerClient(token);const {data:{user}}=await client.auth.getUser(token);if(!user)throw new Error('Your session has expired.');const {data:vendor}=await client.from('vendors').select('id').eq('owner_user_id',user.id).single();if(!vendor)throw new Error('Vendor workspace not found.');const {data:hasAccess}=await client.rpc('vendor_has_platform_access',{target_vendor_id:vendor.id});if(!hasAccess)throw new Error('Your subscription has expired. Renew from Billing to access orders.');return{client,vendor}}
function demoOrders():VendorOrder[]{return[{id:'demo-order-1',order_number:20482,customer_name:'Ada Williams',customer_email:'ada@example.com',customer_phone:'2348012345678',status:'paid',payment_provider:'paystack',payment_reference:'NDH-DEMO-1',currency:'NGN',subtotal:185000,shipping_fee:3500,platform_fee:2775,total:188500,shipping_address:{country_code:'NG',state:'Lagos',zone:'Lagos Island',address:'12 Admiralty Way, Lekki'},customer_note:'Please call before delivery.',paid_at:new Date().toISOString(),created_at:new Date().toISOString(),items:[{id:'demo-item-1',product_id:'p1',variant_id:'x2',product_name:'Raw Vietnamese Wave',variant_description:'24 inches',quantity:1,unit_price:185000,total_price:185000}]},{id:'demo-order-2',order_number:20481,customer_name:'Bola Akin',customer_email:'bola@example.com',customer_phone:'2348098765432',status:'processing',payment_provider:'whatsapp',payment_reference:null,currency:'NGN',subtotal:98000,shipping_fee:2500,platform_fee:1470,total:100500,shipping_address:{country_code:'NG',state:'Lagos',zone:'Lagos Central',address:'Ikeja, Lagos'},customer_note:null,paid_at:null,created_at:new Date(Date.now()-86400000).toISOString(),items:[{id:'demo-item-2',product_id:'p2',variant_id:null,product_name:'The Nia Bob',variant_description:null,quantity:1,unit_price:98000,total_price:98000}]}]}
export const getVendorOrders=createServerFn({method:'GET'}).validator((value:OrderFilters)=>value).handler(async({data})=>{
  const context=await vendorContext();if(!context){const orders=demoOrders().filter(order=>(data.status==='all'||order.status===data.status)&&(!data.search||`${order.order_number} ${order.customer_name} ${order.customer_email}`.toLowerCase().includes(data.search.toLowerCase())));return{configured:false,orders,total:orders.length,page:1,pageSize,summary:{grossNgn:283000,grossUsd:0,feesNgn:4245,feesUsd:0,orders:2}}}
  const page=Math.max(1,Math.floor(data.page)),from=(page-1)*pageSize,to=from+pageSize-1;let query=context.client.from('orders').select('id,order_number,customer_name,customer_email,customer_phone,status,payment_provider,payment_reference,currency,subtotal,shipping_fee,platform_fee,total,shipping_address,customer_note,paid_at,created_at',{count:'exact'}).eq('vendor_id',context.vendor.id).order('created_at',{ascending:false}).range(from,to)
  if(data.status!=='all')query=query.eq('status',data.status)
  const search=data.search.trim().replace(/[,()%]/g,'').slice(0,80);if(search)query=query.or(`customer_name.ilike.%${search}%,customer_email.ilike.%${search}%${/^\d+$/.test(search)?`,order_number.eq.${search}`:''}`)
  const [{data:rows,error,count},{data:summaryRows}]=await Promise.all([query,context.client.from('orders').select('total,platform_fee,status,currency').eq('vendor_id',context.vendor.id).in('status',['paid','processing','fulfilled'])])
  if(error)throw new Error('Unable to load orders.')
  const ids=(rows??[]).map(order=>order.id);const itemResult=ids.length?await context.client.from('order_items').select('id,order_id,product_id,variant_id,product_name,variant_description,quantity,unit_price,total_price').in('order_id',ids):{data:[],error:null};if(itemResult.error)throw new Error('Unable to load order items.')
  const orders=(rows??[]).map(order=>({...order,shipping_address:order.shipping_address as {country_code?:string;state?:string;zone?:string;address?:string}|null,items:(itemResult.data??[]).filter(item=>item.order_id===order.id)})) as VendorOrder[]
  const grossNgn=(summaryRows??[]).filter(row=>row.currency==='NGN').reduce((sum,row)=>sum+row.total,0),grossUsd=(summaryRows??[]).filter(row=>row.currency==='USD').reduce((sum,row)=>sum+row.total,0),feesNgn=(summaryRows??[]).filter(row=>row.currency==='NGN').reduce((sum,row)=>sum+row.platform_fee,0),feesUsd=(summaryRows??[]).filter(row=>row.currency==='USD').reduce((sum,row)=>sum+row.platform_fee,0)
  return{configured:true,orders,total:count??0,page,pageSize,summary:{grossNgn,grossUsd,feesNgn,feesUsd,orders:summaryRows?.length??0}}
})
export const transitionVendorOrder=createServerFn({method:'POST'}).validator((value:{orderId:string;status:OrderStatus;note:string})=>value).handler(async({data})=>{const context=await vendorContext();if(!context)return{ok:true,error:null};const {error}=await context.client.rpc('vendor_transition_order',{target_order_id:data.orderId,new_status:data.status,note:data.note.trim()||undefined});if(error){if(error.message.includes('refunded'))return{ok:false,error:'Paid orders must be refunded before cancellation.'};if(error.message.includes('not allowed'))return{ok:false,error:'That status change is not allowed.'};return{ok:false,error:'Unable to update this order.'}}await dispatchOrderEmails(data.orderId);return{ok:true,error:null}})
export const vendorOrdersQuery=(filters:OrderFilters)=>queryOptions({queryKey:['dashboard','orders',filters],queryFn:()=>getVendorOrders({data:filters}),staleTime:10_000})
