import type {BillingCycle,Product,ProductVariant,SubscriptionStatus,SubscriptionTier,UserRole,Vendor,VendorArchetype} from './schema'

export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[]
type Table<Row extends Record<string,unknown>,Insert extends Record<string,unknown>=Partial<Row>,Update extends Record<string,unknown>=Partial<Insert>>={Row:Row;Insert:Insert;Update:Update;Relationships:[]}
type Timestamped={created_at:string;updated_at:string}
export type UserRow={id:string;email:string;full_name:string;avatar_url:string|null;phone_number:string|null}&Timestamped
export type VendorRow=Omit<Vendor,'design_settings'|'trial_end_date'|'current_period_end'|'meta_capi_token'>&{owner_user_id:string;business_description:string;support_email:string|null;address:Json;social_links:Json;design_settings:Json;trial_end_date:string;current_period_end:string;grace_period_end:string|null;subscription_last_checked_at:string|null;default_currency:string;timezone:string;meta_capi_token_encrypted:string|null;seo_title:string|null;seo_description:string|null;published:boolean}&Timestamped
export type ProductRow=Product&Record<string,unknown>&{slug:string;compare_at_price:number|null;image_urls:Json;is_active:boolean;volume_cbm:number;allocation_threshold:number|null;digital_file_path:string|null;metadata:Json}&Timestamped
export type ProductVariantRow=ProductVariant&Record<string,unknown>&{sku:string|null;attributes:Json}&Timestamped
export type OrderRow={id:string;order_number:number;checkout_token:string;vendor_id:string;customer_id:string|null;customer_email:string;customer_name:string;customer_phone:string|null;status:Database['public']['Enums']['order_status'];payment_provider:Database['public']['Enums']['payment_provider']|null;payment_reference:string|null;currency:string;subtotal:number;shipping_fee:number;platform_fee:number;payment_processing_fee:number;total:number;shipping_address:Json;delivery_zone_id:string|null;customer_note:string|null;metadata:Json;paid_at:string|null}&Timestamped
export interface Database{public:{Tables:{
users:Table<UserRow,{id:string;email:string;full_name?:string;avatar_url?:string|null;phone_number?:string|null}>;
user_roles:Table<{id:string;user_id:string;role:UserRole;created_at:string},{id?:string;user_id:string;role:UserRole}>;
vendors:Table<VendorRow>;
products:Table<ProductRow>;
product_variants:Table<ProductVariantRow>;
shipping_zones:Table<{id:string;vendor_id:string;country_code:string;state:string;zone_name:string;fee:number;estimated_days_min:number|null;estimated_days_max:number|null;active:boolean}&Timestamped>;
cargo_profiles:Table<{id:string;vendor_id:string;name:string;origin_country:string;destination_country:string;transport_mode:'air'|'ocean'|'road'|'rail';metric:'kg'|'cbm'|'flat';rate:number;currency:string;minimum_charge:number;active:boolean}&Timestamped>;
orders:Table<OrderRow>;
order_items:Table<{id:string;order_id:string;product_id:string|null;variant_id:string|null;product_name:string;variant_description:string|null;quantity:number;unit_price:number;weight_kg:number;total_price:number;created_at:string}>;
payouts:Table<{id:string;vendor_id:string;amount:number;currency:string;status:Database['public']['Enums']['payout_status'];bank_account_snapshot:Json;provider_reference:string|null;failure_reason:string|null;requested_at:string;processed_at:string|null}&Timestamped>;
reviews:Table<{id:string;vendor_id:string;product_id:string;customer_id:string|null;order_id:string|null;customer_name:string;rating:number;body:string;is_verified:boolean;is_published:boolean}&Timestamped>;
booking_slots:Table<{id:string;product_id:string;starts_at:string;ends_at:string;capacity:number;reserved_count:number;active:boolean;created_at:string}>;
subscription_events:Table<{id:string;vendor_id:string;provider:Database['public']['Enums']['payment_provider'];provider_reference:string;event_type:string;amount:number|null;payload:Json;created_at:string}>;
exchange_rates:Table<{currency:string;ngn_per_unit:number;updated_at:string}>;
payment_events:Table<{id:string;provider:Database['public']['Enums']['payment_provider'];provider_event_id:string;event_type:string;order_id:string|null;payload:Json;processed:boolean;processing_error:string|null;received_at:string;processed_at:string|null}>;
order_status_history:Table<{id:string;order_id:string;from_status:Database['public']['Enums']['order_status']|null;to_status:Database['public']['Enums']['order_status'];changed_by:string|null;note:string|null;created_at:string}>;
email_messages:Table<{id:string;order_id:string|null;vendor_id:string|null;template:string;recipient_email:string;recipient_name:string;idempotency_key:string;status:Database['public']['Enums']['email_status'];attempts:number;provider_message_id:string|null;last_error:string|null;payload:Json;next_attempt_at:string;sent_at:string|null;created_at:string;updated_at:string}>;
payout_accounts:Table<{id:string;vendor_id:string;bank_code:string;bank_name:string;account_name:string;account_number_last4:string;provider_recipient_code:string;is_default:boolean;verified_at:string;created_at:string;updated_at:string}>;
payout_events:Table<{id:string;payout_id:string;event_type:string;provider_event_id:string|null;payload:Json;created_at:string}>;meta_events:Table<{id:string;vendor_id:string;event_name:string;event_id:string;source_url:string|null;order_id:string|null;payload:Json;provider_response:Json|null;status:string;failure_reason:string|null;created_at:string;sent_at:string|null}>;
};Views:{};Functions:{has_role:{Args:{requested_user_id:string;requested_role:UserRole};Returns:boolean};is_admin:{Args:Record<PropertyKey,never>;Returns:boolean};replace_product_variants:{Args:{target_product_id:string;variants:Json};Returns:undefined};create_storefront_order:{Args:{requested_vendor_slug:string;requested_checkout_token:string;customer:Json;destination:Json;requested_zone_id:string|null;requested_provider:Database['public']['Enums']['payment_provider'];requested_items:Json};Returns:Json};mark_order_paid:{Args:{target_order_id:string;provider_reference:string;paid_payload:Json};Returns:boolean};vendor_transition_order:{Args:{target_order_id:string;new_status:Database['public']['Enums']['order_status'];note?:string};Returns:Database['public']['Tables']['orders']['Row']};vendor_has_platform_access:{Args:{target_vendor_id:string};Returns:boolean};effective_subscription_status:{Args:{target_vendor_id:string};Returns:Database['public']['Enums']['subscription_status']};refresh_vendor_subscription:{Args:{target_vendor_id:string};Returns:Database['public']['Enums']['subscription_status']};vendor_ngn_ledger:{Args:{target_vendor_id:string};Returns:Array<{gross:number;platform_fees:number;processing_fees:number;paid_out:number;pending_payouts:number;available:number}>};request_vendor_payout:{Args:{target_account_id:string;requested_amount:number};Returns:Database['public']['Tables']['payouts']['Row']}};Enums:{app_role:UserRole;vendor_archetype:VendorArchetype;subscription_tier:SubscriptionTier;subscription_status:SubscriptionStatus;billing_cycle:BillingCycle;product_type:'physical'|'booking'|'service'|'digital';order_status:'pending'|'awaiting_payment'|'paid'|'processing'|'fulfilled'|'cancelled'|'refunded';payment_provider:'paystack'|'flutterwave'|'stripe'|'bank_transfer'|'whatsapp';payout_status:'requested'|'processing'|'paid'|'failed'|'cancelled';email_status:'queued'|'sending'|'sent'|'failed'};CompositeTypes:{}}}
